name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Create docker volume if not exists
      run: docker volume create kaiwa-db || true
    - name: Remove previous docker container
      run: docker images -q --filter "reference=kaiwa" | grep -q . && docker rmi -f kaiwa || true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kaiwa
    - name: Run the Docker image
      run: docker run -d --name kaiwa -p 8080:8080 -v kaiwa-db/kaiwa.mv.db:/root/kaiwa.mv.db kaiwa
